# Generated by Django 3.2.7 on 2021-09-21 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='updeted',
            new_name='updated',
        ),
    ]
